### ISSUE TITLE
Broken build on RHEL6.5

### ISSUE THREAD

**Issue by lukas999** [dtrace4linux/linux#91]
While trying to build on RHEL6.5, kernel 2.6.32-431.x86_64, I got the following errors:

...
/root/tmp/dtrace-20141123/build-2.6.32-431.el6.x86_64/driver/ctl.c: In function 'ctl_linux_ioctl':
/root/tmp/dtrace-20141123/build-2.6.32-431.el6.x86_64/driver/ctl.c:271: error: request for member 'val' in something not a structure or union
/root/tmp/dtrace-20141123/build-2.6.32-431.el6.x86_64/driver/ctl.c:279: error: request for member 'val' in something not a structure or union
make[3]: **\* [/root/tmp/dtrace-20141123/build-2.6.32-431.el6.x86_64/driver/ctl.o] Error 1
make[2]: **\* [_module_/root/tmp/dtrace-20141123/build-2.6.32-431.el6.x86_64/driver] Error 2
make[1]: **\* [kernel] Error 2

while running make all.

Possibly relevant information:
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ yum info kernel-headers| grep -E 'Version|Release'
Version     : 2.6.32
Release     : 431.el6
